Add SkeletonView
TouchInstinct/RoboSwag pull request #105
Opened 2019-11-12 09:18 UTC by vender98

2020-10-19 08:13 UTC, vovaksenov99 requested changes

2020-10-19 08:13 UTC, vovaksenov99 commented on views/src/main/res/values/attrs.xml
> +        <!-- Angle of gradient animation direction counting vertical from north. Currently works good with values​from 0 to 60. Default value is 20 -->
пробел. Ты же сказал что не получилось пока это имплементировать? Тогда удали

2020-10-19 09:35 UTC, vovaksenov99 approved these changes

2020-10-19 09:37 UTC, vovaksenov99 requested changes

2020-10-19 09:37 UTC, vovaksenov99 commented on views/src/main/res/values/colors.xml
> +
лишник строки

2020-10-19 09:48 UTC, vovaksenov99 approved these changes

2020-10-19 09:53 UTC, sysoevi approved these changes

2020-10-21 13:34 UTC, NoDopezzz approved these changes

2020-10-21 13:41 UTC, merged