Amount edittext
TouchInstinct/RoboSwag pull request #149
Opened 2020-08-25 08:16 UTC by vovaksenov99

2020-08-25 08:26 UTC, maxbach requested changes
Слишком много непонятного кода. Нужно его разбить по мелким методам, по названию которых будет понятно, что ты будешь проверять.

2020-08-25 08:26 UTC, maxbach commented on views/src/main/java/ru/touchin/widget/AmountWithDecimalDecorator.kt
> +    var decimalSeparator = DEFAULT_DECIMAL_SEPARATOR
Закинь эти три параметра сразу в конструктор

2020-08-25 08:26 UTC, maxbach commented on views/src/main/java/ru/touchin/widget/AmountWithDecimalDecorator.kt
> +            if (isTextWasArtificiallyChanged) {
Слишко ммного кода в одном методе. Подели всю логику по мелким методам

2020-08-25 08:26 UTC, maxbach commented on views/src/main/java/ru/touchin/widget/AmountWithDecimalDecorator.kt
> +    fun getTextWithoutFormatting() = editText.text.toString().withoutFormatting()
В библиотечных классах всегда прописывай возвращаемые классы

2020-08-25 08:26 UTC, maxbach commented on views/src/main/java/ru/touchin/widget/AmountWithDecimalDecorator.kt
> +    private fun setTextWhichWasPasted(text: String) {
setTextWhichWasPasted
Что значит WasPasted? Google translate выдает мне странные переводы

2020-08-25 08:26 UTC, maxbach commented on views/src/main/java/ru/touchin/widget/AmountWithDecimalDecorator.kt
> +        val editText: AppCompatEditText
Просто EditText

2020-08-25 08:28 UTC, vovaksenov99 commented on views/src/main/java/ru/touchin/widget/AmountWithDecimalDecorator.kt
> +    private fun setTextWhichWasPasted(text: String) {
![image](https://user-images.githubusercontent.com/13554528/91151265-1fd22400-e6c6-11ea-97f0-fe268b9774ba.png)

2020-08-25 08:33 UTC, vovaksenov99 commented on views/src/main/java/ru/touchin/widget/AmountWithDecimalDecorator.kt
> +    var decimalSeparator = DEFAULT_DECIMAL_SEPARATOR
Я не смогу это поместить в конструктор
![image](https://user-images.githubusercontent.com/13554528/91151818-d59d7280-e6c6-11ea-8995-f31f8103ebc2.png)

2020-08-25 08:49 UTC, vovaksenov99 commented on views/src/main/java/ru/touchin/widget/AmountWithDecimalDecorator.kt
> +    private fun setTextWhichWasPasted(text: String) {
Придется оставить pasted. 
-Inserted будет занято для другого
-Это именно past т.к так называется кнопка, случай с которой мы обрабатываем.

2020-08-25 08:51 UTC, vovaksenov99 commented on views/src/main/java/ru/touchin/widget/AmountWithDecimalDecorator.kt
> +            if (isTextWasArtificiallyChanged) {
Как смог разнес

2020-08-25 11:07 UTC, RationalEgoism requested changes

2020-08-25 11:07 UTC, RationalEgoism commented on views/src/main/java/ru/touchin/widget/AmountWithDecimalDecorator.kt
> +                    editText.setText("")
textBefore и isTextWasArtificiallyChanged в стартовое состояние

2020-08-25 11:10 UTC, RationalEgoism submitted a review, later dismissed

2020-08-25 11:15 UTC, RationalEgoism approved these changes

2020-08-26 08:14 UTC, maxbach requested changes
Очень много магического не понятного кода. Код нечитаемый и сложный.

2020-08-26 08:14 UTC, maxbach commented on views/src/main/java/ru/touchin/widget/AmountWithDecimalDecorator.kt
> +                    if (text == decimalSeparator || text.count { it == decimalSeparator[0] } > 1 || text.take(2) == "00") {
Я бы немного по-другому разнес.
Каждую проверку с if вынес бы по методам. Каждая проверка возвращает true, если она сработала. Если true, делаешь return

2020-08-26 08:14 UTC, maxbach commented on views/src/main/java/ru/touchin/widget/AmountWithDecimalDecorator.kt
> +                val cursorPos = editText.selectionStart
cursorPosition

2020-08-26 08:14 UTC, maxbach commented on views/src/main/java/ru/touchin/widget/AmountWithDecimalDecorator.kt
> +                    var text = text.toString()
Не понятно по названию, что за переменная

2020-08-26 08:14 UTC, maxbach commented on views/src/main/java/ru/touchin/widget/AmountWithDecimalDecorator.kt
> +        @Suppress("detekt.TooGenericExceptionCaught")
А зачем это, есл здесь нет catch блоков?

2020-08-26 08:14 UTC, maxbach commented on views/src/main/java/ru/touchin/widget/AmountWithDecimalDecorator.kt
> +    private fun setTextWhichWasPasted(text: String) {
А в чем отличие pasted и inserted?

2020-08-26 08:14 UTC, maxbach commented on views/src/main/java/ru/touchin/widget/AmountWithDecimalDecorator.kt
> +    private fun String.prepareForDoubleCast(): String {
Название метода должно прямо говориь, что в нем происходит
prepareForDoubleCase ни о чем не говорит
replaceSeparatorsToDot

2020-08-27 05:10 UTC, vovaksenov99 commented
> Очень много магического не понятного кода. Код нечитаемый и сложный.

Такое случается, когда обрабатываешь тысячу случаев в edittext

2020-08-27 05:14 UTC, vovaksenov99 commented on views/src/main/java/ru/touchin/widget/AmountWithDecimalDecorator.kt
> +        @Suppress("detekt.TooGenericExceptionCaught")
Есть
![image](https://user-images.githubusercontent.com/13554528/91387152-4ebed600-e83d-11ea-8719-b29ead42fcff.png)

2020-08-27 08:31 UTC, maxbach requested changes

2020-08-27 08:31 UTC, maxbach commented on views/src/main/java/ru/touchin/widget/AmountWithDecimalDecorator.kt
> +            if (isTextWasArtificiallyChanged) {
Все, что внутри doOnTextChanged вынеси в отдельный метод. Так init блок укоротишь и избавишься от labeled return

2020-08-27 08:31 UTC, maxbach commented on views/src/main/java/ru/touchin/widget/AmountWithDecimalDecorator.kt
> +                    val textAfter = if (currentText.isNotEmpty()) {
text after what?

2020-08-27 08:31 UTC, maxbach commented on views/src/main/java/ru/touchin/widget/AmountWithDecimalDecorator.kt
> +                } catch (e: Throwable) {
А какой конкретно exception ты здесь ловишь?

2020-08-27 08:31 UTC, maxbach commented on views/src/main/java/ru/touchin/widget/AmountWithDecimalDecorator.kt
> +            result = result.replace(it, ".")
const

2020-08-27 08:31 UTC, maxbach commented on views/src/main/java/ru/touchin/widget/AmountWithDecimalDecorator.kt
> +    private fun setTextWhichWasPasted(text: String) {
Если пользователь ввел новый символ, то так и пиши: onUserNewChar или onNewUserInput

2020-08-27 08:54 UTC, vovaksenov99 commented on views/src/main/java/ru/touchin/widget/AmountWithDecimalDecorator.kt
> +                } catch (e: Throwable) {
Любой. Мне не нужно чтобы вьюха падала при любом вводе. Это страховка

2020-08-27 10:10 UTC, maxbach commented on views/src/main/java/ru/touchin/widget/AmountWithDecimalDecorator.kt
> +                } catch (e: Throwable) {
Похоже на неосмысленный костыль. Зачем тебе ловить exception, если ты делаешь безобидные вещи с вычислением String?

2020-08-27 10:23 UTC, maxbach requested changes

2020-08-27 10:23 UTC, maxbach commented on views/src/main/java/ru/touchin/roboswag/views/widget/AmountWithDecimalDecorator.kt
> +    private fun onTextErased(textAfter: String, cursorPos: Int) {
Название метода должно значить действие. Тут не понятно, что делает метод

2020-08-27 10:23 UTC, maxbach commented on views/src/main/java/ru/touchin/roboswag/views/widget/AmountWithDecimalDecorator.kt
> +    private fun onNewUserInput(textAfter: String, cursorPos: Int) {
Тоже не понятно, какое действие выполняет метод.

2020-08-27 10:23 UTC, maxbach commented on views/src/main/java/ru/touchin/roboswag/views/widget/AmountWithDecimalDecorator.kt
> +                if (!isTextErased(textBefore, formattedText)) {
Переверни if. Можно и без отрицания

2020-08-27 10:23 UTC, maxbach commented on views/src/main/java/ru/touchin/roboswag/views/widget/AmountWithDecimalDecorator.kt
> +            !isSeparatorCutInvalidDecimalLength && currentDecimalPartLength != null
Каждое логическое выражение на отдельной строке

2020-08-27 10:23 UTC, maxbach commented on views/src/main/java/ru/touchin/roboswag/views/widget/AmountWithDecimalDecorator.kt
> +    private fun onNewUserInput(textAfter: String, cursorPos: Int) {
text after what?

2020-08-27 10:23 UTC, maxbach commented on views/src/main/java/ru/touchin/roboswag/views/widget/AmountWithDecimalDecorator.kt
> +    private fun onNewUserInput(textAfter: String, cursorPos: Int) {
cursorPosition

2020-08-27 10:23 UTC, maxbach commented on views/src/main/java/ru/touchin/roboswag/views/widget/AmountWithDecimalDecorator.kt
> +    private fun onNewUserInput(textAfter: String, cursorPos: Int) {
Ну епт, я же уже писал эти комменты. Предлагаю править коммент сразу везде, а не только в том месте, где я его оставлял?

2020-08-27 10:23 UTC, maxbach commented on views/src/main/java/ru/touchin/roboswag/views/widget/AmountWithDecimalDecorator.kt
> +    private var textBefore = ""
text before what?

2020-08-27 11:00 UTC, maxbach approved these changes

2020-08-27 11:04 UTC, RationalEgoism approved these changes

2020-08-27 11:11 UTC, NoDopezzz approved these changes

2020-08-27 11:17 UTC, merged