GroupItemDecoration
TouchInstinct/RoboSwag pull request #150
Opened 2020-08-25 08:24 UTC by RationalEgoism

GroupItemDecoration

2020-08-25 08:28 UTC, maxbach requested changes
Слишком много непонятного кода. Нужно его разбить по мелким методам, по названию которых будет понятно, что ты делаешь

2020-08-25 08:28 UTC, maxbach commented on recyclerview-adapters/src/main/java/ru/touchin/decorators/GroupItemDecoration.kt
> +package ru.touchin.decorators
ru.touchin.roboswag.<Название модуля>.decorators

2020-08-25 11:15 UTC, vovaksenov99 requested changes

2020-08-25 11:15 UTC, vovaksenov99 commented on recyclerview-adapters/src/main/java/ru/touchin/roboswag/recyclerview_adapters/decorators/GroupItemDecoration.kt
> +            }
Наверно можно все в функцию

2020-08-25 11:15 UTC, vovaksenov99 commented on recyclerview-adapters/src/main/java/ru/touchin/roboswag/recyclerview_adapters/decorators/GroupItemDecoration.kt
> +            }
Наверно можно все в функцию

2020-08-25 11:24 UTC, RationalEgoism commented on recyclerview-adapters/src/main/java/ru/touchin/roboswag/recyclerview_adapters/decorators/GroupItemDecoration.kt
> +            }
Не выйдет из-за break

2020-08-25 11:28 UTC, vovaksenov99 approved these changes

2020-08-26 08:21 UTC, maxbach requested changes

2020-08-26 08:21 UTC, maxbach commented on recyclerview-adapters/src/main/java/ru/touchin/roboswag/recyclerview_adapters/decorators/GroupItemDecoration.kt
> +                        break@loop
А зачем label loop, если у тебя нет вложенных циклов?

2020-08-26 08:21 UTC, maxbach commented on recyclerview-adapters/src/main/java/ru/touchin/roboswag/recyclerview_adapters/decorators/GroupItemDecoration.kt
> +                        canvas.restore()
Я думаю, это можно вынести в отдельный метод

2020-08-26 08:24 UTC, maxbach requested changes

2020-08-26 08:24 UTC, maxbach commented on recyclerview-adapters/src/main/java/ru/touchin/roboswag/recyclerview_adapters/decorators/GroupItemDecoration.kt
> +    private fun getWidthChildMeasureSpec(parent: RecyclerView, layoutParams: ViewGroup.MarginLayoutParams, groupView: View): Int {
Можно напрямую, без return

2020-08-26 08:24 UTC, maxbach commented on recyclerview-adapters/src/main/java/ru/touchin/roboswag/recyclerview_adapters/decorators/GroupItemDecoration.kt
> +    private fun getHeightChildMeasureSpec(parent: RecyclerView, layoutParams: ViewGroup.MarginLayoutParams, groupView: View): Int {
Можно напрямую, без return

2020-08-26 08:24 UTC, maxbach commented on recyclerview-adapters/src/main/java/ru/touchin/roboswag/recyclerview_adapters/decorators/GroupItemDecoration.kt
> +    private fun obtainViewHolder(adapterPosition: Int, parent: RecyclerView) = viewHoldersPool[adapterPosition]
В библиотеках нужно четко прописывать возвращаемый тип

2020-08-26 16:01 UTC, RationalEgoism commented on recyclerview-adapters/src/main/java/ru/touchin/roboswag/recyclerview_adapters/decorators/GroupItemDecoration.kt
> +                        break@loop
Нельзя из when { ... } выйти через break/continue без метки

2020-08-27 07:36 UTC, maxbach requested changes

2020-08-27 07:36 UTC, maxbach commented on recyclerview-adapters/src/main/java/ru/touchin/roboswag/recyclerview_adapters/decorators/GroupItemDecoration.kt
> +                        break@loop
Лэйблы полнейшее говно, от которого нужно избавляться любой ценой. Если переделать when на if, то лейблы не нужны

2020-08-27 07:36 UTC, maxbach commented on recyclerview-adapters/src/main/java/ru/touchin/roboswag/recyclerview_adapters/decorators/GroupItemDecoration.kt
> +        var isInvalidated = false
От isInvalidated можно избавиться. Там, где ты сетаешь true  в переменную и делаешь break, можно вызывать метод parent.invalidateItemDecorations и делать reutrn из функции

2020-08-27 07:36 UTC, maxbach commented on recyclerview-adapters/src/main/java/ru/touchin/roboswag/recyclerview_adapters/decorators/GroupItemDecoration.kt
> +        loop@ for (child in parent.children) {
Давай еще по красоте: parent.children.forEach

2020-08-27 09:13 UTC, maxbach approved these changes

2020-08-27 09:33 UTC, merged