fix webview crashes
TouchInstinct/RoboSwag pull request #192
Opened 2021-05-24 15:12 UTC by Rictusempra

fix crash webview when url is blank or invalid
https://jira.touchin.ru/browse/BAN-107

2021-05-25 16:07 UTC, rybakovi commented on webview/src/main/java/ru/touchin/roboswag/webview/web_view/BaseWebViewClient.kt
> +     * onReceivedError don't calls when url is "about:blank" (url string isBlank)
наверное isn't called корректнее

2021-05-25 16:08 UTC, rybakovi commented on webview/src/main/java/ru/touchin/roboswag/webview/web_view/BaseWebView.kt
> +                useWideViewPort = true
за что отвечают эти две строки?

2021-05-25 16:10 UTC, Rictusempra commented on webview/src/main/java/ru/touchin/roboswag/webview/web_view/BaseWebView.kt
> +                useWideViewPort = true
Это подстраивает страницу под размер экрана и отключает горизонтальный скролл (как раньше было, из-за него страница при прокрутке ездила)

2021-05-26 08:50 UTC, sysoevi commented on webview/src/main/java/ru/touchin/roboswag/webview/web_view/BaseWebView.kt
> +        binding.webView.loadUrl(url ?: String())
Может лучше `url ?: ""`, чтобы каждый раз не создавать новую строку в куче ?

2021-05-26 09:29 UTC, NoDopezzz requested changes

2021-05-26 09:29 UTC, NoDopezzz commented on webview/src/main/java/ru/touchin/roboswag/webview/web_view/BaseWebViewClient.kt
> +import android.webkit.*
Пофикси импорты

2021-05-26 09:29 UTC, NoDopezzz commented on webview/src/main/java/ru/touchin/roboswag/webview/web_view/BaseWebViewClient.kt
> +        if (error.errorCode != -10 || error.errorCode == -2) {
Если `errorCode == -10`, то он никогда не будет равным `-2`, бессмысленная проверка получается

2021-05-26 09:29 UTC, NoDopezzz commented on webview/src/main/java/ru/touchin/roboswag/webview/web_view/BaseWebViewClient.kt
> +        }
Может есть смысл это поставить перед?
```
if (!isError) {
            callback.onPageCookiesLoaded(CookieManager.getInstance().getCookie(url).processCookies())
        }
```

2021-05-26 09:29 UTC, NoDopezzz commented on webview/src/main/java/ru/touchin/roboswag/webview/web_view/BaseWebViewClient.kt
> +     * onPageFinished calls always, but after onReceivedError
is called

2021-05-26 09:29 UTC, NoDopezzz commented on webview/src/main/java/ru/touchin/roboswag/webview/web_view/BaseWebViewClient.kt
> +     * onPageFinished calls always, but after onReceivedError
Можешь перевести коммент?)
- onPageFinished вызывается всегда, кроме того случая если передним вызывается onReceivedError
- onPageFinished вызывается всегда, но после onReceivedError

Лучше сделать коммент более читабельным

2021-05-26 09:38 UTC, Rictusempra commented on webview/src/main/java/ru/touchin/roboswag/webview/web_view/BaseWebViewClient.kt
> +        if (error.errorCode != -10 || error.errorCode == -2) {
Честно говоря я даже не знаю, что за код -10, он тут уже был, при отсутствии интернета и невалидной ссылке всегда выдаёт -2. Если это уже кем-то предусмотренная ошибка, то всё равно логично, что перейдёт в ERROR

2021-05-26 11:59 UTC, NoDopezzz commented on webview/src/main/java/ru/touchin/roboswag/webview/web_view/BaseWebViewClient.kt
> +     * кроме случая, когда в кэше есть страница для ошибки -2 и сначала вызывается onReceivedError
Не, комменты на английском. Я имел в виду перевести чисто для меня)

2021-05-26 11:59 UTC, NoDopezzz commented on webview/src/main/java/ru/touchin/roboswag/webview/web_view/BaseWebViewClient.kt
> +        if (error.errorCode != -10 || error.errorCode == -2) {
Я к тому, что вся проверка логически бессмысленная. Зачем тут `-2`?
Неправильность `error.errorCode != -10` (т.е. errorCode равен 10) исключает правильность `error.errorCode == -2`

2021-05-26 13:11 UTC, Rictusempra commented on webview/src/main/java/ru/touchin/roboswag/webview/web_view/BaseWebViewClient.kt
> +     * кроме случая, когда в кэше есть страница для ошибки -2 и сначала вызывается onReceivedError
Для некоторых сайтов, как на банках, после первой загрузки с интернетом в кэшэ сохраняется их страница для ошибки, если она есть, то сначала вызывается onPageFinished, а уже потом onReceivedError

2021-05-27 11:10 UTC, sysoevi approved these changes

2021-05-27 11:16 UTC, NoDopezzz approved these changes

2021-05-27 11:20 UTC, rybakovi approved these changes

2021-05-27 11:21 UTC, merged