Add/web view callback
TouchInstinct/RoboSwag pull request #194
Opened 2021-06-09 22:13 UTC by sousnein

Теперь по клику на урлу внутри WebView можно  кидать любой экшн

2021-06-10 06:10 UTC, NoDopezzz requested changes

2021-06-10 06:10 UTC, NoDopezzz commented on webview/src/main/java/ru/touchin/roboswag/webview/web_view/BaseWebViewClient.kt
> +                && callback.actionOnRedirectInsideWebView(webView = view, url = url) != null
Не очень читаемая логика
Лучше написать что-то такое
```
return if (!callback.onOverrideUrlLoading(url) && view.originalUrl != null) {
      callback.actionOnRedirectInsideWebView(webView = view, url = url)
      true
} else {
      false
}
```

2021-06-10 06:10 UTC, NoDopezzz commented on webview/src/main/java/ru/touchin/roboswag/webview/web_view/BaseWebViewClient.kt
> +                }
Поправь стили

2021-06-10 06:13 UTC, rybakovi commented on webview/src/main/java/ru/touchin/roboswag/webview/web_view/BaseWebViewClient.kt
> -import android.webkit.CookieManager
импорты тоже поправь

2021-06-10 13:05 UTC, NoDopezzz requested changes

2021-06-10 13:05 UTC, NoDopezzz commented on webview/src/main/java/ru/touchin/roboswag/webview/web_view/WebViewCallback.kt
> +
Теперь непонятно, зачем возвращаемое значение

2021-06-10 13:05 UTC, NoDopezzz commented on webview/src/main/java/ru/touchin/roboswag/webview/web_view/BaseWebView.kt
> +
Можешь убрать = и написать просто в `{...}`

2021-06-10 13:26 UTC, NoDopezzz approved these changes

2021-06-10 13:28 UTC, rybakovi approved these changes

2021-06-11 07:24 UTC, sysoevi approved these changes

2021-06-11 07:25 UTC, merged