create captcha module with checking
TouchInstinct/RoboSwag pull request #248
Opened 2022-03-15 08:46 UTC by rinstance

2022-03-15 12:26 UTC, Qwaey submitted a review, later dismissed

2022-03-15 13:11 UTC, NoDopezzz requested changes

2022-03-15 13:11 UTC, NoDopezzz commented on recaptcha/src/main/java/ru/touchin/recaptcha/RecaptchaController.kt
> +        }
Получается не очень гибкая и расширяемая система. Предлагаю немного поменять подход. Создать интерфейс `CaptchClient`, у которого будет один метод `showCaptcha`. Этот интерфейс будут имплементить два класса `GoogleCaptchaClient` и `HuaweiCaptchaClient`.

Метод объекта `ServicesUtils` будет возвращать не `boolean`, а экземпляр `enum` `MobileService`: `HuaweiService` или `GoogleService`.
В `CaptchaManager` будет хранится мапа `<MobileService, CaptchClient>`.

В таком случае добавить новую реализацию (или изменить текущую) в исходном классн понадобится просто изменить мапу

2022-03-15 13:12 UTC, NoDopezzz commented on recaptcha/src/main/java/ru/touchin/recaptcha/RecaptchaController.kt
> +        private val activity: Activity,
И скорее просто `Captcha`
Капча - это все таки алгоритм, а `reCAPTCHA` - гугловская технология

2022-03-16 15:33 UTC, rinstance commented
Создал модуль `client-services` и перенёс туда `ServicesUtils`
Порефакторил замечания по комментам

2022-03-16 18:14 UTC, NoDopezzz requested changes

2022-03-16 18:14 UTC, NoDopezzz commented on client-services/build.gradle
> +        }
А у HMS нет никакого core или base? Не хочется тянуть целую либу с `safetydetect`

2022-03-16 18:14 UTC, NoDopezzz commented on recaptcha/src/main/java/ru/touchin/recaptcha/CaptchaManager.kt
> +
Все комменты на английском пишем. Старайся писать документацию в JavaDoc стиле
Вот тут можно почитать об этом https://www.oracle.com/ru/technical-resources/articles/java/javadoc-tool.html

2022-03-16 18:14 UTC, NoDopezzz commented on recaptcha/src/main/java/ru/touchin/recaptcha/CaptchaManager.kt
> +        onNewTokenReceived: (String) -> Unit,
Почему `onNewTokenReceived` публичный?

2022-03-16 18:14 UTC, NoDopezzz commented on recaptcha/src/main/java/ru/touchin/recaptcha/HuaweiCaptchaClient.kt
> +        huaweiSafetyDetectClient.initUserDetect()
`.initUserDetect()` на следующей строке

2022-03-16 18:14 UTC, NoDopezzz commented on recaptcha/README.md
> +Для использования модуля нужно добавить json файл с сервисами в корневую папку проекта
Что-то более общее, но более содержательное. 
Примерный план:
1. Общее описание
2. Требования (json'ы)
3. Пример использования

2022-03-17 11:48 UTC, NoDopezzz commented on recaptcha/README.md
> +)
Это настоящий ключ? Если да, то лучше убрать) Roboswag все таки публичная либа

2022-03-17 13:23 UTC, rinstance commented on recaptcha/README.md
> +)
Я в [05f2adb](https://github.com/TouchInstinct/RoboSwag/pull/248/commits/05f2adb849158848de8973e6ee90e7cea425e60c) коммите менял)
![image](https://user-images.githubusercontent.com/30986957/158817710-2ffc6e71-3ffa-4a46-a1a9-994830bf38cf.png)

2022-03-17 13:25 UTC, NoDopezzz approved these changes

2022-03-17 13:29 UTC, merged