Add alerts module
TouchInstinct/RoboSwag pull request #265
Opened 2022-08-10 07:47 UTC by tonlirise

Alerts
----
[INTERNAL-339](https://jira.touchin.ru/browse/INTERNAL-339): Интеграция со "старой" системой построения UI
[INTERNAL-340](https://jira.touchin.ru/browse/INTERNAL-340): Интеграция с новой системой построения UI
[INTERNAL-341](https://jira.touchin.ru/browse/INTERNAL-341): ok, retry, yes/no
[INTERNAL-342](https://jira.touchin.ru/browse/INTERNAL-342): Возможность создания кастомного представления алерта и его презентации
[INTERNAL-343](https://jira.touchin.ru/browse/INTERNAL-343): Набор методов для быстрого создания и презентации алертов в пару строк кода

2022-09-13 13:34 UTC, AnadolStudio commented on alerts/README.md
> +alerts
Не должно ли с большой начинаться?)

2022-09-13 13:35 UTC, AnadolStudio commented on alerts/README.md
> +* dialogLayout - id кастомного layout (по умолчанию R.layout.dialog_alert)
По правилам хорошего тона оформления перечислений, после каждого пункта должна быть точка с запятой. В последнем пункте точка

2022-09-13 13:37 UTC, AnadolStudio commented on alerts/README.md
> +* onNegativeAction - колбэк при нажатии на левую кнопку,
Аналогично

2022-09-13 13:38 UTC, AnadolStudio commented on alerts/README.md
> +                activity,
Если именовать параметры, то тогда уж все

2022-09-13 13:44 UTC, AnadolStudio commented on alerts/src/main/java/ru/touchin/roboswag/composable_dialog/ComposableAlertDialog.kt
> +}
```kt
                        TextButton(
                                onClick = {
                                    onPositiveAction?.invoke()
                                    isDialogOpen.value = false
                                }
                        ) {
                            Text(positiveButtonText.orEmpty())
                        }
```

```kt
                                    TextButton(
                                            onClick = {
                                                onNegativeAction?.invoke()
                                                isDialogOpen.value = false
                                            }
                                    ) {
                                        Text(positiveText)
                                    }
```

Явное дублирование кода. 
DRY
Создай отдельный метод

2022-09-13 13:47 UTC, AnadolStudio commented on alerts/src/main/java/ru/touchin/roboswag/viewable_dialog/AlertDialogManager.kt
> +                }
Я возможно не до конца понимаю ситуацию, но почему show вызывается до setupAlertDialog в apply {}
Обычно .show() всегда идет в конце. Тут случаем багов нет?

2022-09-13 13:47 UTC, AnadolStudio commented on alerts/src/main/java/ru/touchin/roboswag/viewable_dialog/AlertDialogManager.kt
> +
Лишняя пустая строка

2022-09-13 13:48 UTC, AnadolStudio commented on alerts/src/main/java/ru/touchin/roboswag/viewable_dialog/AlertDialogManager.kt
> +        }
можно написать так 
```kt
with (dialog) {
        setCancelable(cancelable)
        setOnDismissListener { onCancelAction() }
        findViewById<TextView>(R.id.alert_title)?.setTextOrGone(title)
        findViewById<TextView>(R.id.alert_message)?.setTextOrGone(message)
        findViewById<TextView>(R.id.alert_positive_button)?.let { buttonView ->
            setupButton(dialog, buttonView, positiveButtonText, onPositiveClick)
        }
        findViewById<TextView>(R.id.alert_negative_button)?.let { buttonView ->
            setupButton(dialog, buttonView, negativeButtonText, onNegativeClick)
        }
}
```

2022-09-13 13:50 UTC, AnadolStudio commented on alerts/src/main/java/ru/touchin/roboswag/viewable_dialog/AlertDialogManager.kt
> +            dialog: androidx.appcompat.app.AlertDialog,
Тут без всего импорта не обойтись? На гите не вижу таковых причин, возможно что-то упускаю

2022-09-13 13:51 UTC, AnadolStudio commented on alerts/src/main/java/ru/touchin/roboswag/viewable_dialog/AlertDialogManager.kt
> +            onCancelAction: () -> Unit = {}
onCancel обязателен?
А если он скажем не нужен в рамках моих задач?
Может сделать его nullable?

2022-09-13 13:56 UTC, AnadolStudio commented on alerts/src/main/java/ru/touchin/roboswag/viewable_dialog/AlertDialogUtils.kt
> +    }
1) избыточное условие
2) используется НЕ (!) в условии, когда без этого явно можно обойтись (это правила хорошего тона условий)
3) Почему нельзя сделать так:
```kt
    isVisible = !text.isNullOrEmpty()
    setText(text)
```
2 строки против 6))

2022-09-13 14:03 UTC, AnadolStudio commented on alerts/src/main/java/ru/touchin/roboswag/composable_dialog/ComposableAlertDialog.kt
> +                    title = customTitle ?: { Text(title.orEmpty()) },
Избавляемся от лишней вложенности 
if (!isDialogOpen.value) return

2022-09-13 14:03 UTC, AnadolStudio commented on alerts/src/main/java/ru/touchin/roboswag/composable_dialog/ComposableAlertDialog.kt
> +
пустая строка в перечислении  параметров

2022-09-13 14:03 UTC, AnadolStudio commented on alerts/src/main/java/ru/touchin/roboswag/composable_dialog/ComposableAlertDialog.kt
> +
пустая стсрока

2022-09-13 14:04 UTC, AnadolStudio commented on alerts/src/main/java/ru/touchin/roboswag/composable_dialog/ComposableAlertDialog.kt
> +
почему тут есть вообще пустые строки, это же не метод

2022-09-13 14:05 UTC, AnadolStudio commented on alerts/src/main/java/ru/touchin/roboswag/composable_dialog/ComposableAlertDialog.kt
> +                            }
кажется лишние скобки

2022-09-13 14:05 UTC, AnadolStudio commented on alerts/src/main/java/ru/touchin/roboswag/composable_dialog/ComposableAlertDialog.kt
> +                            }
Либо я чего-то не понимаю, ибо выше так же сделано

2022-09-13 14:06 UTC, AnadolStudio commented on alerts/src/main/java/ru/touchin/roboswag/composable_dialog/ComposableAlertDialog.kt
> +    fun ShowAlertDialog(
ммм, почему метод с большой?

2022-09-13 14:08 UTC, AnadolStudio commented on alerts/src/main/java/ru/touchin/roboswag/composable_dialog/ComposableAlertDialog.kt
> +    var customNegativeBtn: @Composable (() -> Unit)? = null
Почему мы не прокидываем это в рамках метода, например,
На это есть технические причины из-за @Composable?

2022-09-13 14:09 UTC, AnadolStudio commented on alerts/src/main/java/ru/touchin/roboswag/composable_dialog/ComposableAlertDialog.kt
> +        if (isDialogOpen.value) {
Избавляемся от лишней вложенности
if (!isDialogOpen.value) return

2022-09-13 14:11 UTC, AnadolStudio commented on alerts/build.gradle
> +    implementation("com.google.android.material:material")
А почему тут версии не указываются?

2022-09-13 14:16 UTC, AnadolStudio commented on alerts/src/main/java/ru/touchin/roboswag/composable_dialog/ComposableAlertDialog.kt
> +                                    }
мне в целом не нравится как тут это записано
Это явно можно сделать симпатичнее

2022-09-13 14:19 UTC, AnadolStudio commented on alerts/src/main/java/ru/touchin/roboswag/composable_dialog/ComposableAlertDialog.kt
> +                                    }
Как вариант 
```kt
 dismissButton = when {
                customNegativeBtn != null -> customNegativeBtn
                negativeBtnTitle != null -> TextButton(
                              onClick = {
                                  onNegativeAction?.invoke()
                                  isDialogOpen.value = false
                              }
                ) { Text(positiveText) }
                else -> null
```

2022-09-13 14:21 UTC, AnadolStudio requested changes
Понимаю, что большая часть комментов относится не к твоему труду, но это точно нужно править

2022-09-15 13:56 UTC, anastasiyaK97 commented on alerts/README.md
> +alerts
Ну заголовок = название модуля. Можно и так оставить

2022-09-15 14:46 UTC, anastasiyaK97 commented on alerts/src/main/java/ru/touchin/roboswag/viewable_dialog/AlertDialogManager.kt
> +                }
Тут поинт скорее всего был в том, чтобы была возможность уже AlertDialog настроить, найти вьюхи на нем через findViewById например, он должен уже быть построен, и метод show его как раз строит

2022-09-15 14:48 UTC, anastasiyaK97 commented on alerts/src/main/java/ru/touchin/roboswag/composable_dialog/ComposableAlertDialog.kt
> +    fun ShowAlertDialog(
Насколько я понимаю, в Composable так принято

2022-09-15 14:50 UTC, anastasiyaK97 commented on alerts/src/main/java/ru/touchin/roboswag/composable_dialog/ComposableAlertDialog.kt
> +    var customNegativeBtn: @Composable (() -> Unit)? = null
Не знаю, почему так сделано было

2022-09-15 14:52 UTC, anastasiyaK97 commented on alerts/build.gradle
> +    implementation("com.google.android.material:material")
Ну есть constraints

2022-09-15 16:21 UTC, AnadolStudio commented on alerts/README.md
> +alerts
Много заголовков, которые начинаются с маленькой буквы знаешь?)

2022-09-15 16:21 UTC, AnadolStudio commented on alerts/src/main/java/ru/touchin/roboswag/composable_dialog/ComposableAlertDialog.kt
> +    var customNegativeBtn: @Composable (() -> Unit)? = null
Принял

2022-09-15 16:21 UTC, AnadolStudio commented on alerts/src/main/java/ru/touchin/roboswag/composable_dialog/ComposableAlertDialog.kt
> +    fun ShowAlertDialog(
Принял

2022-09-15 16:23 UTC, AnadolStudio commented on alerts/src/main/java/ru/touchin/roboswag/viewable_dialog/AlertDialogManager.kt
> +
пустая строка

2022-09-15 16:25 UTC, AnadolStudio commented on alerts/build.gradle
> +    implementation("com.google.android.material:material")
а, увидел, оки

2022-09-15 16:28 UTC, AnadolStudio commented on alerts/src/main/java/ru/touchin/roboswag/viewable_dialog/AlertDialogManager.kt
> +                }
Ага, оки

2022-09-15 16:32 UTC, AnadolStudio submitted a review, later dismissed

2022-09-16 08:15 UTC, anastasiyaK97 submitted a review, later dismissed

2022-09-16 08:41 UTC, anastasiyaK97 approved these changes

2022-09-16 08:41 UTC, merged