Update yandex map version
TouchInstinct/RoboSwag pull request #282
Opened 2023-02-15 17:51 UTC by styni

- Обновил версию карт до 4.2.2
- Добавил отдельные методы для добавления/удаления листенеров на тап (раньше он почему-то вешался вместе с добавлением пинов на карту)

2023-02-15 18:54 UTC, rybakovi requested changes

2023-02-15 18:54 UTC, rybakovi commented on yandex-map/build.gradle
> +                require '4.2.2-full'
а full это разве не версия с расширенным функционалом для коммерческой платной подписки?

2023-02-16 07:00 UTC, styni commented on yandex-map/build.gradle
> +                require '4.2.2-full'
// Облегченная библиотека, содержит только карту, слой пробок, 
    // LocationManager, UserLocationLayer и возможность скачивать офлайн-карты (только в платной версии).
    implementation 'com.yandex.android:maps.mobile:4.2.2-lite'

    // Полная библиотека в дополнение к lite версии предоставляет автомобильную маршрутизацию, 
    // веломаршрутизацию, пешеходную маршрутизацию и маршрутизацию на общественном транспорте, 
    // поиск, suggest, геокодирование и отображение панорам.
    // implementation 'com.yandex.android:maps.mobile:4.2.2-full'

Достаточно, наверное lite версии, но как я понял, к платной оно никак не относится, в платной только ключ новый скорее всего и через него регулируется кол-во запросов и тд

2023-02-16 07:26 UTC, petropavel13 commented on yandex-map/build.gradle
> +                require '4.2.2-full'
никакой веломаршрутизации нам пока не надо) давайте lite

2023-02-16 07:44 UTC, styni commented on yandex-map/build.gradle
> +                require '4.2.2-full'
готово

2023-02-20 08:19 UTC, rybakovi approved these changes

2023-02-20 08:20 UTC, merged